branch-defaults:
  master:
    environment: dev-conventionbot
    group_suffix: null
global:
  application_name: conventionbot
  default_ec2_keyname: convention-bot-eb
  default_platform: Docker 1.11.1
  default_region: us-east-1
  profile: bf-openlab
  sc: git
